# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

set --prepend fish_function_path /nix/store/qd6v3w2733w99494lbzdh10ip2dj3cps-fishplugin-foreign-env-unstable-2020-02-09/share/fish/vendor_functions.d
fenv source /home/dlan/.nix-profile/etc/profile.d/hm-session-vars.sh > /dev/null
set -e fish_function_path[1]

# vi-mode
fish_vi_key_bindings
# nix
if test -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  fenv source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
end
# home-manager in fish config
if test -e ~/.NIX_PATH.sh
   fenv source ~/.NIX_PATH.sh
end
# nnn in fish config
set -x NNN_PLUG 'f:finder;o:fzopen;P:mocq;d:diffs;t:nmount;v:imgview'
set -x NNN_BMS  'd:$HOME/Documents;D:$HOME/Downloads;h:$HOME'
set -x NNN_FCOLORS 'c1e2272e006033f7c6d6abc4'
set fzf_preview_dir_cmd exa --all --color=always
set fzf_preview_file_cmd bat
set fzf_fd_opts --hidden --exclude=.git
# alias
alias flsof4="lsof -Pn -i4 | awk '{printf \"%10s %6s %5s %4s %-20s\n\", \$1, \$2, \$3, \$8, \$9}' | fzf --border --cycle --ansi --header-lines=1"
alias fp="cat /etc/services | fzf"
alias gcob='git checkout $(git branch | fzf --cycle --border --ansi)'
alias vim='nvim'
alias vi='nvim'
alias view='nvim -RM'
alias ls='exa --icons --color=always --group-directories-first'
alias ll='exa -alF --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias l='exa -F --icons --color=always --group-directories-first'
alias l.='exa -a | egrep "^\."'
alias mans='tldr'
alias nix-sha256='nix-prefetch-url --unpack'
alias rm='trash'
# 啟動direnv
direnv hook fish | source
# 安裝非free的套件所需要的
set -x NIXPKGS_ALLOW_UNFREE 1
# imput method
set -x XMODIFIERS @im=ibus
set -x QT_IM_MODULE @im=ibus
set -x GTK_IM_MODULE @im=ibus


status --is-login; and begin

  # Login shell initialisation
  

end

status --is-interactive; and begin

  # Abbreviations
  

  # Aliases
  alias vimdiff 'nvim -d'

  # Interactive shell intialisation
  # add completions generated by Home Manager to $fish_complete_path
begin
  set -l joined (string join " " $fish_complete_path)
  set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
  set -l post_joined (string replace $prev_joined "" $joined)
  set -l prev (string split " " (string trim $prev_joined))
  set -l post (string split " " (string trim $post_joined))
  set fish_complete_path $prev "/home/dlan/.local/share/fish/home-manager_generated_completions" $post
end


end
